local prefix = "packages.ol.pkg.ol_mou.skills."

return {
  require(prefix .. "zhuri"),
  require(prefix .. "ranji"),
  require(prefix .. "zhaxiang"),
  require(prefix .. "hongtu"),
  require(prefix .. "qiwu"),

  require(prefix .. "weilin"),
  require(prefix .. "duoshou"),
  require(prefix .. "guanbian"),
  require(prefix .. "xiongni"),
  require(prefix .. "fengshang"),
  require(prefix .. "zhibing"),

  require(prefix .. "liwen"),
  require(prefix .. "zhengyi"),

  require(prefix .. "dulie"),
  require(prefix .. "douchan"),
  require(prefix .. "hulie"),
  require(prefix .. "yipo"),
  require(prefix .. "hetao"),
  require(prefix .. "shenli"),
  require(prefix .. "yufeng"),
  require(prefix .. "shishou"),
  require(prefix .. "bojue"),
  require(prefix .. "yangwei"),
  require(prefix .. "zhuijiao"),
  require(prefix .. "choulie"),

  require(prefix .. "jinming"),
  require(prefix .. "xiaoshi"),
  require(prefix .. "yanliang"),
  require(prefix .. "yanliang_active"),

  require(prefix .. "jigu"),
  require(prefix .. "jiewan"),
  require(prefix .. "jiewan_active"),
  require(prefix .. "jiewan_viewas"),
  require(prefix .. "jiaodi"),
  require(prefix .. "baojing"),
  require(prefix .. "bingcai"),
  require(prefix .. "lixian"),
  require(prefix .. "guliang"),
  require(prefix .. "xutu"),
  require(prefix .. "jingxian"),
  require(prefix .. "xiayong"),
  require(prefix .. "nilan"),
  require(prefix .. "jueya"),
}